import type { Metadata } from "next";

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";

import { AnonymousCartProvider } from "@/modules/cart/components/anonymous-cart-provider";
import { CartSheet } from "@/modules/cart/components/cart-sheet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AnonymousCartProvider>
      <Navbar />
      {children}
      <Footer />
      <CartSheet />
    </AnonymousCartProvider>
  );
}
