import type { Metadata } from "next";

import { RootProvider } from "fumadocs-ui/provider";

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootProvider>
      <Navbar />
      {children}
      <Footer />
    </RootProvider>
  );
}
