import type { Metadata } from "next";
import Link from "next/link";

import { BoxIcon, ChartLine, HouseIcon, PanelsTopLeftIcon, SettingsIcon, UsersRoundIcon } from "lucide-react";

import { AppNavbar } from "@/components/layout/app-navbar";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudioLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Tabs defaultValue="tab-1">
      <div className="sticky top-0 z-999 bg-card">
        <AppNavbar />
        <ScrollArea>
          <TabsList className="h-auto w-full gap-2 rounded-none border-b bg-transparent py-1 text-foreground">
            <div className="container w-full">
              <Link href="/studio">
                <TabsTrigger
                  className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                  value="tab-1"
                >
                  <HouseIcon aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                  Overview
                </TabsTrigger>
              </Link>
              <Link href="/studio/products">
                <TabsTrigger
                  className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                  value="tab-2"
                >
                  <PanelsTopLeftIcon aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                  Products
                </TabsTrigger>
              </Link>
              <TabsTrigger
                className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                value="tab-3"
              >
                <BoxIcon aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                Coupons
              </TabsTrigger>
              <TabsTrigger
                className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                value="tab-4"
              >
                <UsersRoundIcon aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                Users
              </TabsTrigger>
              <TabsTrigger
                className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                value="tab-5"
              >
                <ChartLine aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                Orders
              </TabsTrigger>
              <TabsTrigger
                className="after:-mb-1.5 relative after:absolute after:inset-x-0 after:bottom-0 after:h-0.5 hover:bg-accent hover:text-foreground data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:hover:bg-accent data-[state=active]:after:bg-primary"
                value="tab-6"
              >
                <SettingsIcon aria-hidden="true" className="-ms-0.5 me-1.5 opacity-60" size={16} />
                Settings
              </TabsTrigger>
            </div>
          </TabsList>
          <ScrollBar orientation="horizontal" />
        </ScrollArea>
      </div>
      {children}
    </Tabs>
  );
}
