import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudioLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SidebarProvider>
    //   <AppSidebar />
    //   <SidebarInset>{children}</SidebarInset>
    // </SidebarProvider>
    <>{children}</>
  );
}
