import type { Metadata } from "next";
import "../styles/globals.css";

import { geist, helvetica } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geist.className, helvetica.variable)}>{children}</body>
    </html>
  );
}
