import type { Metadata } from "next";
import "../styles/globals.css";

import { Navbar } from "@/components/layout/navbar";
import { Toaster } from "@/components/ui/sonner";

import { geist, helvetica } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(helvetica.className, geist.variable)}>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
